### PR TITLE
unicode support

### PR DESCRIPTION
**Pull request by jane567**
in #39 etc

### CODE REVIEW

**Comment by Neo23x0** [comment]
Looks great. Thanks

**Comment by Neo23x0** [comment]
Which platform and python version do you use. 
I noticed that Python 2.7.11 32bit crashes on Windows.

**Comment by Neo23x0** [comment]
Ha - I fixed that too. 
Python crashes completely when passing a unicode string as variable to the YARA module's match function. I remove unicode characters from the variables passed to YARA though.

**Comment by Neo23x0** [comment]
Do you have a Twitter handle? I would like to mention your support in the tweet.

**Comment by jane567** [comment]
Thanks!

But unfortunately I do not have active Twitter account. May be I open it near
future ..

. 

  4/30/2016, 6:00:47 PM пользователь Florian Roth (notifications@github.com)
  написал:


  Do you have a Twitter handle? I would like to mention your support in the
  tweet.

**Comment by jane567** [comment]
Yes, I use 2.7.11, but 64 bit version

. 

  4/30/2016, 5:22:38 PM пользователь Florian Roth (notifications@github.com)
  написал:


  Which platform and python version do you use.
  I noticed that Python 2.7.11 32bit crashes on Windows.

**Pull request merged**
